### ISSUE TITLE
Persist verifier monitoring after agent restarts

### ISSUE THREAD

**Issue by lukehinds** [keylime/enhancements#1]
# Persist verifier monitoring after agent restarts
- Persist verifier monitoring after agent restarts
- Keylime Enhancement Proposal: https://github.com/keylime/enhancements/pull/2
- Primary contact (assignee): @lukehinds 
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please to keep this description up to date._

**Comment by mpeters** [comment]
This enhancement has been implemented
