### ISSUE TITLE
Migrate CI to github actions

### ISSUE THREAD

**Issue by lukehinds** [keylime/enhancements#18]
# Enhancement Description
- One-line enhancement description (can be used as a release note): Port CI to github actions
- Keylime Enhancement Proposal: (link to keylime/enhancements file, if none yet, link to PR)
- Primary contact (assignee): @mbestavros 
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please to keep this description up to date._

**Comment by mbestavros** [comment]
@lukehinds Do we think this can be closed now that the migration is done?

**Comment by mpeters** [comment]
yep
