### ISSUE TITLE
Expand agent_uuid to have "kubernetes" as an option

### ISSUE THREAD

**Issue by mpeters** [keylime/enhancements#21]
# Enhancement Description
Allow `agent_uuid` to have a value of "kubernetes" and to retrieve the node name from K8s APIs

- Keylime Enhancement Proposal: TBD
- Primary contact (assignee): @mpeters 
- Enhancement target (which target equals to which milestone):
  - Alpha release target: TBD
  - Beta release target: TBD
  - Stable release target: TBD

Right now `agent_uuid` in the `cloud_agent` section of keylime.conf can be one of: `generate`, `hash_ek`, `openstack` or a bare string. I'm proposing a new option `kubernetes` that will retrieve the target node's ID from the K8s APIs and use that as the keylime agent's UUID (similar to what openstack does for openstack hosts).

**Comment by THS-on** [comment]
New uuid features should just use the `environment` option.
