### ISSUE TITLE
Improve project layout

### ISSUE THREAD

**Issue by kaifeng** [keylime/enhancements#4]
# Enhancement Description
- Improve project layout
- Keylime Enhancement Proposal: (link to keylime/enhancements file, if none yet, link to PR)
- Primary contact (assignee): @kaifeng
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

**Comment by lukehinds** [comment]
I think this is complete now @kaifeng ?

**Comment by kaifeng** [comment]
It's hard to say a hard limit for this enhancement, I did plan to substract common bits to a common place, but yeah, I guess we can iterate from here.
