### ISSUE TITLE
TPM 2.0 Preboot Event log support

### ISSUE THREAD

**Issue by maugustosilva** [keylime/enhancements#40]
# Enhancement Description
- TPM 2.0 Preboot Event log support
- [Description](https://github.com/keylime/keylime/issues/491) and [First PR](https://github.com/keylime/keylime/pull/517)
- Primary contact (assignee): @maugustosilva
- Enhancement target (which target equals to which milestone):
  - Alpha release target (TBD)
  - Beta release target (TBD)
  - Stable release target (TBD)

_Please to keep this description up to date._

**Comment by mpeters** [comment]
@maugustosilva we're using the enhancements repo not for issues for enhancements, but to create design documents for the enhancments. We're mirroring a system that K8s, tekton and many others use.

Can you create a new PR with the enhancement doc based on the template?

**Comment by mpeters** [comment]
@maugustosilva I believe this enhancement issue can be closed, correct?

**Comment by maugustosilva** [comment]
Yes, absolutely, fully implemented. Please close it.
