### ISSUE TITLE
Let the agent provide contact IP and port

### ISSUE THREAD

**Issue by THS-on** [keylime/enhancements#50]
# Enhancement Description
- One-line enhancement description (can be used as a release note): Let the agent provide contact IP and port to the registrar for the verifier.
- Keylime Enhancement Proposal: #49 
- Primary contact (assignee): @THS-on
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please to keep this description up to date._

**Comment by mpeters** [comment]
@THS-on I believe this enhancement issue can be closed, correct?

**Comment by THS-on** [comment]
Yes this is fully implemented.
