### ISSUE TITLE
Support Agents behind firewalls and proxies

### ISSUE THREAD

**Issue by DanielFroehlich** [keylime/enhancements#57]
# Enhancement Description
- One-line enhancement description (can be used as a release note): Support Agents behind firewalls and proxies
- Keylime Enhancement Proposal: (link to keylime/enhancements file, if none yet, link to PR)
- Primary contact (assignee):
- Enhancement target (which target equals to which milestone):
  - Alpha release target (x.y)
  - Beta release target (x.y)
  - Stable release target (x.y)

_Please to keep this description up to date._

**Comment by THS-on** [comment]
Closing in favor of #60.
