### ISSUE TITLE
GSOC 2023

### ISSUE THREAD

**Issue by reveurguy** [keylime/enhancements#95]
I would like to work upon #61 (Enhance Web UI) for GSOC, if Keylime is taking part this season.

**Comment by THS-on** [comment]
We removed the Web UI last year and currently I think it is unlikely that we add one back, because all current users integrate Keylime into different systems directly. 

@mpeters @maugustosilva what do you think?

**Comment by mpeters** [comment]
I think he might be talking about the website itself (http://keylime.dev).

**Comment by reveurguy** [comment]
I meant the one described in the gsoc idea.
For the website as well i have opened an issue but that is different from this.

**Comment by mpeters** [comment]
Ah, I think you meant the GSOC idea from 2022. Yeah, that won't be a good task for 2023 as we did remove that old web UI.
